name: snapd-desktop-integration
base: core22
adopt-info: snapd-desktop-integration
summary: Desktop Integration for snapd
description: |
  Provides a user session daemon used to provide a bridge between
  the user's session and snapd.  Used for things like automatic
  theme installation.

grade: stable
confinement: strict

slots:
  # for GtkApplication registration
  snapd-desktop-integration:
    interface: dbus
    bus: session
    name: io.snapcraft.desktop-integration

apps:
  snapd-desktop-integration:
    extensions: [gnome]
    command: bin/snapd-desktop-integration
    daemon: simple
    passthrough: #///! TODO: Remove once daemon-scope lands in snapcraft
      daemon-scope: user
    restart-condition: always
    plugs:
      - snap-themes-control

slots:
  snapd-desktop-integration:
    interface: dbus
    bus: session
    name: io.snapcraft.SnapDesktopIntegration

parts:
  snapd-glib:
    source: https://github.com/snapcore/snapd-glib
    source-type: git
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Ddocs=false
      - -Dintrospection=false
      - -Dvala-bindings=false
      - -Dqt-bindings=false
      - -Dqml-bindings=false
    build-packages:
      - libpolkit-gobject-1-dev
    prime:
      - usr/lib/*/libsnapd-glib-2.so.*

  snapd-desktop-integration:
    after: [ snapd-glib ]
    source: .
    plugin: meson
    meson-parameters:
      - --prefix=/
    build-packages:
      - jq
    override-build: |
      craftctl default
      craftctl set version="$(meson introspect . --projectinfo |
          jq -r .version)"
