name: snapd-desktop-integration
base: core22
adopt-info: snapd-desktop-integration
summary: Desktop Integration for snapd
description: |
  Provides a user session daemon used to provide a bridge between
  the user's session and snapd.  Used for things like automatic
  theme installation.

grade: stable
confinement: strict

layout:
  /usr/share/locale:
    bind: $SNAP/usr/share/locale

plugs:
  snap:
    interface: system-files
    read:
      - /snap

apps:
  snapd-desktop-integration:
    extensions: [gnome]
    command: usr/bin/snapd-desktop-integration
    daemon: simple
    passthrough: #///! TODO: Remove once daemon-scope lands in snapcraft
      daemon-scope: user
    restart-condition: on-success
    restart-delay: 2s
    plugs:
      - snap-themes-control
      - login-session-observe
      - snap

slots:
  snapd-desktop-integration:
    interface: dbus
    bus: session
    name: io.snapcraft.SnapDesktopIntegration

parts:
  snapd-glib:
    source: https://github.com/snapcore/snapd-glib
    source-type: git
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Ddocs=false
      - -Dintrospection=false
      - -Dvala-bindings=false
      - -Dqt6=false
      - -Dqml-bindings=false
      - -Dsoup2=true
    build-packages:
      - libpolkit-gobject-1-dev
    prime:
      - usr/lib/*/libsnapd-glib.so.*

  snapd-desktop-integration:
    after: [ snapd-glib ]
    source: .
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - jq
    override-build: |
      craftctl default
      craftctl set version="$(meson introspect . --projectinfo |
          jq -r .version)"
