name: snapd-desktop-integration
base: core18
adopt-info: desktop-integration
summary: Desktop Integration for snapd
description: |
  Provides a user session daemon used to provide a bridge between
  the user's session and snapd.  Used for things like automatic
  theme installation.

grade: devel
confinement: strict

apps:
  snapd-desktop-integration:
    extensions: [gnome-3-34]
    command: bin/snapd-desktop-integration
    plugs:
      - snapd-control

parts:
  desktop-integration:
    source: .
    plugin: meson
    meson-parameters:
      - --prefix=/
    build-packages:
      - jq
      - libsnapd-glib-dev
    override-build: |
      snapcraftctl build
      snapcraftctl set-version "$(meson introspect ./snapbuild --projectinfo |
          jq -r .version)"
  libraries:
    plugin: nil
    stage-packages:
      - libsnapd-glib1
    prime:
      - usr/lib/*/libsnapd-glib.so.*
