name: tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-snap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v4
      with:
        name: 'snap'
        path: ${{ steps.snapcraft.outputs.snap}}
  unitary-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y meson ninja-build jq libsnapd-glib-dev
      - name: Build
        run: |
          meson setup _build
          ninja -C _build
      - name: Test theme change
        run: |
          ./_build/tests/test-snapd-desktop-integration

