name: tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unitary-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y meson ninja-build jq libgtk-4-dev libnotify-dev libsoup-3.0-dev libjson-glib-dev libpolkit-gobject-1-dev weston gcovr librsvg2-2 xwayland-run
      - name: Build snapd-glib
        run: |
          git clone https://github.com/snapcore/snapd-glib.git
          cd snapd-glib
          meson setup _build --prefix=/usr -Ddocs=false -Dintrospection=false -Dvala-bindings=false -Dqt5=false -Dqt6=false -Dqml-bindings=false -Dtests=false -Dexamples=false
          ninja -C _build
          sudo ninja -C _build install
          cd ..
      - name: Build libnotify
        run: |
          git clone https://gitlab.gnome.org/GNOME/libnotify.git
          cd libnotify
          meson setup _build --prefix=/usr \
            -Dgtk_doc=false \
            -Dman=false \
            -Dintrospection=disabled \
            -Dtests=false
          ninja -C _build
          sudo ninja -C _build install
          cd ..
      - name: Build
        run: |
          meson setup _build
          ninja -C _build
      - name: Test theme change
        run: |
          # can't use XVFB because gtk_settings uses Xsettings by default, but we need to use keyfile backend
          wlheadless-run -c weston -- ./_build/tests/test-snapd-desktop-integration
      - name: Test notices monitor
        run: |
          ./_build/tests/test-sdi-notices-monitor
      - name: Test Dock progress bar
        run: |
          ./_build/tests/test-sdi-progress-dock
      - name: Test notifications
        run: |
          ./_build/tests/test-sdi-notify
      - name: Test refresh monitor
        run: |
          ./_build/tests/test-refresh-monitor
      - name: Test progress window
        run: |
          wlheadless-run -c weston -- ./_build/tests/test-sdi-progress-window
